# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'metal3DUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1257, 506)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 323, 396))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.b0001radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.b0001radioButton.setObjectName("b0001radioButton")
        self.horizontalLayout.addWidget(self.b0001radioButton)
        self.b001radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.b001radioButton.setObjectName("b001radioButton")
        self.horizontalLayout.addWidget(self.b001radioButton)
        self.b1radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.b1radioButton.setObjectName("b1radioButton")
        self.horizontalLayout.addWidget(self.b1radioButton)
        self.b10radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.b10radioButton.setObjectName("b10radioButton")
        self.horizontalLayout.addWidget(self.b10radioButton)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 0, 1, 1)
        self.PORTlistWidget = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.PORTlistWidget.setObjectName("PORTlistWidget")
        self.gridLayout.addWidget(self.PORTlistWidget, 1, 0, 1, 1)
        self.RATElistWidget = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.RATElistWidget.setObjectName("RATElistWidget")
        item = QtWidgets.QListWidgetItem()
        self.RATElistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.RATElistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.RATElistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.RATElistWidget.addItem(item)
        self.gridLayout.addWidget(self.RATElistWidget, 2, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.BUNKER1_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.BUNKER1_checkBox.setObjectName("BUNKER1_checkBox")
        self.gridLayout_2.addWidget(self.BUNKER1_checkBox, 2, 0, 1, 1)
        self.RF_HOME_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.RF_HOME_pushButton.setObjectName("RF_HOME_pushButton")
        self.gridLayout_2.addWidget(self.RF_HOME_pushButton, 0, 1, 1, 1)
        self.LB_HOME_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.LB_HOME_pushButton.setObjectName("LB_HOME_pushButton")
        self.gridLayout_2.addWidget(self.LB_HOME_pushButton, 1, 1, 1, 1)
        self.RB_HOME_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.RB_HOME_pushButton.setObjectName("RB_HOME_pushButton")
        self.gridLayout_2.addWidget(self.RB_HOME_pushButton, 0, 0, 1, 1)
        self.LT_HOME_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.LT_HOME_pushButton.setObjectName("LT_HOME_pushButton")
        self.gridLayout_2.addWidget(self.LT_HOME_pushButton, 1, 0, 1, 1)
        self.BUNKER2_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.BUNKER2_checkBox.setObjectName("BUNKER2_checkBox")
        self.gridLayout_2.addWidget(self.BUNKER2_checkBox, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 5, 0, 1, 1)
        self.CONNECTpushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.CONNECTpushButton.setObjectName("CONNECTpushButton")
        self.gridLayout.addWidget(self.CONNECTpushButton, 3, 0, 1, 1)
        self.REFRESHpushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.REFRESHpushButton.setObjectName("REFRESHpushButton")
        self.gridLayout.addWidget(self.REFRESHpushButton, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.horizontalLayout_3.addWidget(self.lcdNumber_2)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lcdNumber = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout_3.addWidget(self.lcdNumber)
        self.gridLayout.addLayout(self.horizontalLayout_3, 7, 0, 1, 1)
        self.LEFT_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.LEFT_pushButton.setGeometry(QtCore.QRect(370, 260, 81, 81))
        self.LEFT_pushButton.setAutoRepeat(True)
        self.LEFT_pushButton.setAutoRepeatDelay(500)
        self.LEFT_pushButton.setObjectName("LEFT_pushButton")
        self.UP_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.UP_pushButton.setGeometry(QtCore.QRect(440, 190, 81, 81))
        self.UP_pushButton.setAutoRepeat(True)
        self.UP_pushButton.setAutoRepeatDelay(500)
        self.UP_pushButton.setObjectName("UP_pushButton")
        self.DOWN_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.DOWN_pushButton.setGeometry(QtCore.QRect(440, 330, 81, 81))
        self.DOWN_pushButton.setAutoRepeat(True)
        self.DOWN_pushButton.setAutoRepeatDelay(500)
        self.DOWN_pushButton.setObjectName("DOWN_pushButton")
        self.RIGHT_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.RIGHT_pushButton.setGeometry(QtCore.QRect(510, 260, 81, 81))
        self.RIGHT_pushButton.setAutoRepeat(True)
        self.RIGHT_pushButton.setAutoRepeatDelay(500)
        self.RIGHT_pushButton.setObjectName("RIGHT_pushButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(359, 14, 271, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.LAYER_lcdNumber = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.LAYER_lcdNumber.setObjectName("LAYER_lcdNumber")
        self.horizontalLayout_2.addWidget(self.LAYER_lcdNumber)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget.setGeometry(QtCore.QRect(640, 10, 601, 451))
        self.openGLWidget.setObjectName("openGLWidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 410, 321, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.horizontalLayout_4.addWidget(self.lcdNumber_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.b0001radioButton.setText(_translate("MainWindow", "0.01mm"))
        self.b001radioButton.setText(_translate("MainWindow", "0.1mm"))
        self.b1radioButton.setText(_translate("MainWindow", "1.0mm"))
        self.b10radioButton.setText(_translate("MainWindow", "10.0mm"))
        __sortingEnabled = self.RATElistWidget.isSortingEnabled()
        self.RATElistWidget.setSortingEnabled(False)
        item = self.RATElistWidget.item(0)
        item.setText(_translate("MainWindow", "115200"))
        item = self.RATElistWidget.item(1)
        item.setText(_translate("MainWindow", "57600"))
        item = self.RATElistWidget.item(2)
        item.setText(_translate("MainWindow", "38400"))
        item = self.RATElistWidget.item(3)
        item.setText(_translate("MainWindow", "9600"))
        self.RATElistWidget.setSortingEnabled(__sortingEnabled)
        self.BUNKER1_checkBox.setText(_translate("MainWindow", "BUNKER 1"))
        self.RF_HOME_pushButton.setText(_translate("MainWindow", "RF_HOME"))
        self.LB_HOME_pushButton.setText(_translate("MainWindow", "LB_HOME"))
        self.RB_HOME_pushButton.setText(_translate("MainWindow", "RB_HOME"))
        self.LT_HOME_pushButton.setText(_translate("MainWindow", "LT_HOME"))
        self.BUNKER2_checkBox.setText(_translate("MainWindow", "BUNKER 2"))
        self.CONNECTpushButton.setText(_translate("MainWindow", "connect"))
        self.REFRESHpushButton.setText(_translate("MainWindow", "refresh"))
        self.label_2.setText(_translate("MainWindow", "LIFT:"))
        self.label_3.setText(_translate("MainWindow", "RACK:"))
        self.LEFT_pushButton.setText(_translate("MainWindow", "<"))
        self.UP_pushButton.setText(_translate("MainWindow", "^"))
        self.DOWN_pushButton.setText(_translate("MainWindow", "v"))
        self.RIGHT_pushButton.setText(_translate("MainWindow", ">"))
        self.label.setText(_translate("MainWindow", "LAYER:"))
        self.label_4.setText(_translate("MainWindow", "STATE:"))

