# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'metal3DUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 760)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 1101, 731))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(260, 70, 611, 471))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.PORTlistWidget = QtWidgets.QListWidget(self.verticalLayoutWidget_3)
        self.PORTlistWidget.setObjectName("PORTlistWidget")
        self.verticalLayout_3.addWidget(self.PORTlistWidget)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox)
        self.REFRESHpushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.REFRESHpushButton.setObjectName("REFRESHpushButton")
        self.verticalLayout_3.addWidget(self.REFRESHpushButton)
        self.CONNECTpushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.CONNECTpushButton.setObjectName("CONNECTpushButton")
        self.verticalLayout_3.addWidget(self.CONNECTpushButton)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_2.sizePolicy().hasHeightForWidth())
        self.textBrowser_2.setSizePolicy(sizePolicy)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout_3.addWidget(self.textBrowser_2)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(2, 1)
        self.verticalLayout_3.setStretch(3, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 1081, 111))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_7.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_7.addWidget(self.pushButton_4)
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_7.addWidget(self.pushButton_6)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.pushButton_7 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_2.addWidget(self.pushButton_7)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 130, 351, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.horizontalLayout_2.addWidget(self.lcdNumber_2)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.horizontalLayout_5.addWidget(self.lcdNumber_3)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.horizontalLayout_6.addWidget(self.lcdNumber_4)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lcdNumber = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout_4.addWidget(self.lcdNumber)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_5.sizePolicy().hasHeightForWidth())
        self.lcdNumber_5.setSizePolicy(sizePolicy)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.horizontalLayout_3.addWidget(self.lcdNumber_5)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.LAYER_lcdNumber = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.LAYER_lcdNumber.setObjectName("LAYER_lcdNumber")
        self.horizontalLayout_8.addWidget(self.LAYER_lcdNumber)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout.setStretch(5, 1)
        self.verticalLayout.setStretch(6, 1)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(720, 130, 375, 351))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.b0001radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.b0001radioButton.setChecked(True)
        self.b0001radioButton.setObjectName("b0001radioButton")
        self.horizontalLayout.addWidget(self.b0001radioButton)
        self.b001radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.b001radioButton.setObjectName("b001radioButton")
        self.horizontalLayout.addWidget(self.b001radioButton)
        self.b1radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.b1radioButton.setObjectName("b1radioButton")
        self.horizontalLayout.addWidget(self.b1radioButton)
        self.b10radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.b10radioButton.setObjectName("b10radioButton")
        self.horizontalLayout.addWidget(self.b10radioButton)
        self.CONT_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.CONT_radioButton.setObjectName("CONT_radioButton")
        self.horizontalLayout.addWidget(self.CONT_radioButton)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.RIGHT_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RIGHT_pushButton.sizePolicy().hasHeightForWidth())
        self.RIGHT_pushButton.setSizePolicy(sizePolicy)
        self.RIGHT_pushButton.setAutoRepeat(True)
        self.RIGHT_pushButton.setAutoRepeatDelay(500)
        self.RIGHT_pushButton.setObjectName("RIGHT_pushButton")
        self.gridLayout_5.addWidget(self.RIGHT_pushButton, 1, 3, 1, 1)
        self.UP_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UP_pushButton.sizePolicy().hasHeightForWidth())
        self.UP_pushButton.setSizePolicy(sizePolicy)
        self.UP_pushButton.setAutoRepeat(True)
        self.UP_pushButton.setAutoRepeatDelay(500)
        self.UP_pushButton.setObjectName("UP_pushButton")
        self.gridLayout_5.addWidget(self.UP_pushButton, 0, 2, 1, 1)
        self.LEFT_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEFT_pushButton.sizePolicy().hasHeightForWidth())
        self.LEFT_pushButton.setSizePolicy(sizePolicy)
        self.LEFT_pushButton.setAutoRepeat(True)
        self.LEFT_pushButton.setAutoRepeatDelay(500)
        self.LEFT_pushButton.setObjectName("LEFT_pushButton")
        self.gridLayout_5.addWidget(self.LEFT_pushButton, 1, 1, 1, 1)
        self.DOWN_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DOWN_pushButton.sizePolicy().hasHeightForWidth())
        self.DOWN_pushButton.setSizePolicy(sizePolicy)
        self.DOWN_pushButton.setAutoRepeat(True)
        self.DOWN_pushButton.setAutoRepeatDelay(500)
        self.DOWN_pushButton.setObjectName("DOWN_pushButton")
        self.gridLayout_5.addWidget(self.DOWN_pushButton, 2, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_5)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 570, 1091, 131))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget_5)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_5.addWidget(self.textBrowser)
        self.FLUSH_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        self.FLUSH_checkBox.setCheckable(True)
        self.FLUSH_checkBox.setChecked(True)
        self.FLUSH_checkBox.setObjectName("FLUSH_checkBox")
        self.verticalLayout_5.addWidget(self.FLUSH_checkBox)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(370, 130, 341, 351))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("дфдфд")
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setChecked(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_6.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_6.addWidget(self.pushButton_3)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(10, 490, 1091, 80))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.RB_HOME_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RB_HOME_pushButton.sizePolicy().hasHeightForWidth())
        self.RB_HOME_pushButton.setSizePolicy(sizePolicy)
        self.RB_HOME_pushButton.setObjectName("RB_HOME_pushButton")
        self.horizontalLayout_9.addWidget(self.RB_HOME_pushButton)
        self.RF_HOME_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RF_HOME_pushButton.sizePolicy().hasHeightForWidth())
        self.RF_HOME_pushButton.setSizePolicy(sizePolicy)
        self.RF_HOME_pushButton.setObjectName("RF_HOME_pushButton")
        self.horizontalLayout_9.addWidget(self.RF_HOME_pushButton)
        self.LT_HOME_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LT_HOME_pushButton.sizePolicy().hasHeightForWidth())
        self.LT_HOME_pushButton.setSizePolicy(sizePolicy)
        self.LT_HOME_pushButton.setObjectName("LT_HOME_pushButton")
        self.horizontalLayout_9.addWidget(self.LT_HOME_pushButton)
        self.LB_HOME_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LB_HOME_pushButton.sizePolicy().hasHeightForWidth())
        self.LB_HOME_pushButton.setSizePolicy(sizePolicy)
        self.LB_HOME_pushButton.setObjectName("LB_HOME_pushButton")
        self.horizontalLayout_9.addWidget(self.LB_HOME_pushButton)
        self.BUNKER1_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BUNKER1_pushButton.sizePolicy().hasHeightForWidth())
        self.BUNKER1_pushButton.setSizePolicy(sizePolicy)
        self.BUNKER1_pushButton.setCheckable(True)
        self.BUNKER1_pushButton.setObjectName("BUNKER1_pushButton")
        self.horizontalLayout_9.addWidget(self.BUNKER1_pushButton)
        self.BUNKER2_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BUNKER2_pushButton.sizePolicy().hasHeightForWidth())
        self.BUNKER2_pushButton.setSizePolicy(sizePolicy)
        self.BUNKER2_pushButton.setCheckable(True)
        self.BUNKER2_pushButton.setObjectName("BUNKER2_pushButton")
        self.horizontalLayout_9.addWidget(self.BUNKER2_pushButton)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(10, 10, 871, 681))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.horizontalLayoutWidget_10)
        self.openGLWidget.setObjectName("openGLWidget")
        self.horizontalLayout_10.addWidget(self.openGLWidget)
        self.verticalSlider = QtWidgets.QSlider(self.horizontalLayoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalSlider.sizePolicy().hasHeightForWidth())
        self.verticalSlider.setSizePolicy(sizePolicy)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.horizontalLayout_10.addWidget(self.verticalSlider)
        self.horizontalLayout_10.setStretch(0, 1)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(890, 10, 191, 241))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.lcdNumber_6 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_7)
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.verticalLayout_7.addWidget(self.lcdNumber_6)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.lcdNumber_7 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_7)
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.verticalLayout_7.addWidget(self.lcdNumber_7)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "9600"))
        self.comboBox.setItemText(1, _translate("MainWindow", "38400"))
        self.comboBox.setItemText(2, _translate("MainWindow", "57600"))
        self.comboBox.setItemText(3, _translate("MainWindow", "115200"))
        self.REFRESHpushButton.setText(_translate("MainWindow", "ОБНОВИТЬ"))
        self.CONNECTpushButton.setText(_translate("MainWindow", "ПОДКЛЮЧИТСЯ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "ПОДКЛЮЧЕНИЕ"))
        self.pushButton_5.setText(_translate("MainWindow", "СТАРТ"))
        self.pushButton_4.setText(_translate("MainWindow", "СТОП"))
        self.pushButton_6.setText(_translate("MainWindow", "ПАУЗА"))
        self.pushButton_7.setText(_translate("MainWindow", "СТАРТ СО СЛОЯ"))
        self.label_4.setText(_translate("MainWindow", "ТЕКУЩЕЕ СОСТОЯНИЕ:"))
        self.label_5.setText(_translate("MainWindow", "ВСЕГО СЛОЕВ:"))
        self.label.setText(_translate("MainWindow", "ТЕКУЩИЙ СЛОЙ:"))
        self.label_3.setText(_translate("MainWindow", "ПОЗ РАКЕЛЯ:"))
        self.label_6.setText(_translate("MainWindow", "ВРЕМЯ С НАЧАЛА ЦИКЛА:"))
        self.label_2.setText(_translate("MainWindow", "ПОЗ ЛИФТА:"))
        self.b0001radioButton.setText(_translate("MainWindow", "0.01mm"))
        self.b001radioButton.setText(_translate("MainWindow", "0.1mm"))
        self.b1radioButton.setText(_translate("MainWindow", "1.0mm"))
        self.b10radioButton.setText(_translate("MainWindow", "10.0mm"))
        self.CONT_radioButton.setText(_translate("MainWindow", "cont"))
        self.RIGHT_pushButton.setText(_translate("MainWindow", ">"))
        self.UP_pushButton.setText(_translate("MainWindow", "^"))
        self.LEFT_pushButton.setText(_translate("MainWindow", "<"))
        self.DOWN_pushButton.setText(_translate("MainWindow", "v"))
        self.FLUSH_checkBox.setText(_translate("MainWindow", "ОЧИЩАТЬ КОНСОЛЬ"))
        self.pushButton_2.setText(_translate("MainWindow", "сканатор жарит"))
        self.pushButton.setText(_translate("MainWindow", "сканатор забивает"))
        self.pushButton_3.setText(_translate("MainWindow", "ракель жарит"))
        self.RB_HOME_pushButton.setText(_translate("MainWindow", "РАКЕЛЬ ДОМ ^"))
        self.RF_HOME_pushButton.setText(_translate("MainWindow", "РАКЕЛЬ ДОМ v"))
        self.LT_HOME_pushButton.setText(_translate("MainWindow", "ЛИФТ ДОМ ^"))
        self.LB_HOME_pushButton.setText(_translate("MainWindow", "ЛИФТ ДОМ v"))
        self.BUNKER1_pushButton.setText(_translate("MainWindow", "БУНКЕР 1"))
        self.BUNKER2_pushButton.setText(_translate("MainWindow", "БУНКЕР 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "УПРАВЛЕНИЕ"))
        self.label_7.setText(_translate("MainWindow", "ПРОСМАТРИВАЕМЫЙ СЛОЙ"))
        self.label_8.setText(_translate("MainWindow", "ВСЕГО СЛОЕВ:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "СЛОИ"))

